

export interface RespuestaEventosHoy {
  status: string;
  articles: Article[];
}

export interface Article {
  id: number;
  name: string;
  active: boolean;
  user_id: boolean;
  company_id: (number | string)[];
  organizer_id: boolean;
  event_type_id: (number | string)[];
  color: number;
  event_mail_ids: any[];
  seats_max: number;
  seats_availability: string;
  seats_min: number;
  seats_reserved: number;
  seats_available: number;
  seats_unconfirmed: number;
  seats_used: number;
  registration_ids: any[];
  date_tz: string;
  date_begin: string;
  date_end: string;
  state: string;
  auto_confirm: boolean;
  is_online: boolean;
  address_id: boolean;
  country_id: boolean;
  twitter_hashtag: boolean;
  description: string;
  badge_front: boolean;
  badge_back: boolean;
  badge_innerleft: boolean;
  badge_innerright: boolean;
  event_logo: boolean;
  website_meta_title: boolean;
  website_meta_description: boolean;
  website_meta_keywords: boolean;
  website_meta_og_img: boolean;
  website_id: boolean;
  is_published: boolean;
  website_menu: boolean;
  menu_id: boolean;
  track_ids: any[];
  sponsor_ids: any[];
  website_track: boolean;
  website_track_proposal: boolean;
  track_menu_ids: any[];
  track_proposal_menu_ids: any[];
  allowed_track_tag_ids: any[];
  tracks_tag_ids: any[];
  clase: string;
  idioma: string;
  lista_de_funciones: string;
  sala_id: boolean;
  titulo_original: string;
  url_trailer: string;
  url_imagen: boolean;
  imagen: boolean;
  message_follower_ids: number[];
  message_ids: number[];
  message_main_attachment_id: boolean;
  website_message_ids: any[];
  create_uid: (number | string)[];
  create_date: string;
  write_uid: (number | string)[];
  write_date: string;
  seats_expected: number;
  date_begin_located: string;
  date_end_located: string;
  is_seo_optimized: boolean;
  website_url: string;
  website_published: boolean;
  is_participating: boolean;
  track_count: number;
  sponsor_count: number;
  message_is_follower: boolean;
  message_partner_ids: number[];
  message_channel_ids: any[];
  message_unread: boolean;
  message_unread_counter: number;
  message_needaction: boolean;
  message_needaction_counter: number;
  message_has_error: boolean;
  message_has_error_counter: number;
  message_attachment_count: number;
  display_name: string;
  __last_update: string;
}
